	<script src="<?=$url?>js/jquery-min.js"></script>
	<script src="<?=$url?>js/popper.min.js"></script>
	<script src="<?=$url?>js/bootstrap.min.js"></script>
	<script src="<?=$url?>js/owl.carousel.js"></script> 
	<script src="<?=$url?>js/jquery.mixitup.js"></script>       
	<script src="<?=$url?>js/jquery.nav.js"></script>    
	<script src="<?=$url?>js/scrolling-nav.js"></script>    
	<script src="<?=$url?>js/jquery.easing.min.js"></script>     
	<script src="<?=$url?>js/wow.js"></script>   
	<script src="<?=$url?>js/jquery.counterup.min.js"></script>     
	<script src="<?=$url?>js/nivo-lightbox.js"></script>     
	<script src="<?=$url?>js/jquery.magnific-popup.min.js"></script>     
	<script src="<?=$url?>js/waypoints.min.js"></script>      
	<script src="<?=$url?>js/form-validator.min.js"></script>
	<script src="<?=$url?>js/contact-form-script.js"></script>   
	<script src="<?=$url?>js/main.js"></script>
