	<link rel="stylesheet" href="<?=$url?>css/bootstrap.min.css">
	<link rel="stylesheet" href="<?=$url?>css/line-icons.css">
	<link rel="stylesheet" href="<?=$url?>css/owl.carousel.css">
	<link rel="stylesheet" href="<?=$url?>css/owl.theme.css">
	<link rel="stylesheet" href="<?=$url?>css/animate.css">
	<link rel="stylesheet" href="<?=$url?>css/magnific-popup.css">
	<link rel="stylesheet" href="<?=$url?>css/nivo-lightbox.css">
	<link rel="stylesheet" href="<?=$url?>css/main.css">    
	<link rel="stylesheet" href="<?=$url?>css/responsive.css">